---
title: |
  <center> University of Edinburgh, School of Mathematics </center>
  <center> Incomplete Data Analysis, 2020/2021 </center>
  <center> Assignment 1 </center>
author: "Zeming Liang"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

3. (a)  

```{r, include = TRUE, message = FALSE}
n <- 500
set.seed(1)
z1 <- rnorm(n, 0, 1)
z2 <- rnorm(n, 0, 1)
z3 <- rnorm(n, 0, 1)
y1 <- z1 + 1
y2 <- 5 + 2*z1 + z2
y_ori <- data.frame(y1, y2)
y2_mar <- ifelse(2*(y1-1) + z3 < 0, NA, y2)
y_mar <- data.frame(y1, y2_mar)
y2_MAR_obs <- y2_mar[!is.na(y2_mar)]
plot(density(y2), lwd = 2, col = "blue", 
     xlab = "Y2", main = "MAR simulation",
     ylim = c(0, 0.25))
lines(density(y2_MAR_obs), lwd = 2, col = "red")
legend(9, 0.25, 
       legend = c("Complete data", "Observed data"), 
       col = c("blue", "red"), 
       lty = c(1, 1), lwd = c(2, 2), bty = "n",
       cex = 0.85)
```

3. (b)

```{r, include = TRUE, message = FALSE}
fit <- lm(y2_mar ~ y1, data = y_mar)
#summary(fit)

set.seed(1)
predy2_sri <- predict(fit, newdata = y_mar) + rnorm(n, 0, sigma(fit))
y2_sri <- ifelse(is.na(y2_mar) == TRUE, predy2_sri, y2_mar)

plot(density(y2), lwd = 2, col = "blue", 
     xlab = "Y2", main = "MAR stochastic regression imputation",
     ylim = c(0, 0.25))
lines(density(y2_sri), lwd = 2, col = "red")
legend(9, 0.25, 
       legend = c("Complete data", "Completed data"), 
       col = c("blue", "red"), 
       lty = c(1, 1), lwd = c(2, 2), bty = "n",
       cex = 0.85)
```

3. (c)

```{r, include = TRUE, message = FALSE}
y2_mnar <- ifelse(2*(y2-5) + z3 < 0, NA, y2)
y_mnar <- data.frame(y1, y2_mnar)
y2_MNAR_obs <- y2_mnar[!is.na(y2_mnar)]
plot(density(y2), lwd = 2, col = "blue", 
     xlab = "Y2", main = "MNAR simulation",
     ylim = c(0, 0.35))
lines(density(y2_MNAR_obs), lwd = 2, col = "red")
legend(9, 0.35, 
       legend = c("Complete data", "Observed data"), 
       col = c("blue", "red"), 
       lty = c(1, 1), lwd = c(2, 2), bty = "n",
       cex = 0.85)
```

3. (d)
```{r, include = TRUE, message = FALSE}
fit2 <- lm(y2_mnar ~ y1, data = y_mnar)
#summary(fit2)

set.seed(1)
predy2_sri2 <- predict(fit2, newdata = y_mnar) + rnorm(n, 0, sigma(fit2))
y2_sri2 <- ifelse(is.na(y2_mnar) == TRUE, predy2_sri2, y2_mnar)

plot(density(y2), lwd = 2, col = "blue", 
     xlab = "Y2", main = "MNAR stochastic regression imputation",
     ylim = c(0, 0.25))
lines(density(y2_sri2), lwd = 2, col = "red")
legend(9, 0.25, 
       legend = c("Complete data", "Completed data"), 
       col = c("blue", "red"), 
       lty = c(1, 1), lwd = c(2, 2), bty = "n",
       cex = 0.85)
```


4. (a)

```{r, include = TRUE, message = FALSE}
load("C:/Users/DELL/Desktop/databp.Rdata")
ind <- which(!is.na(databp$recovtime)) #indices of subjects with rt observed
mrt <- mean(databp$recovtime, na.rm = T)
sert <- sd(databp$recovtime, na.rm = TRUE)/sqrt(length(ind))
data.frame(mrt, sert)
corcc <- cor(databp, method = "pearson", use = "complete")
corrd <- corcc[1,3]
corrb <- corcc[2,3]
data.frame(corrd, corrb)
```


4. (b)

```{r, include = TRUE, message = FALSE}
rtmi <- ifelse(is.na(databp$recovtime), mrt, databp$recovtime)
databpmi <- data.frame(databp[,1:2],rtmi)
n <- length(rtmi)
mmi <- mean(rtmi)
semi <- sd(rtmi)/sqrt(n)
data.frame(mmi, semi)
cormi <- cor(databpmi, method = "pearson")
corrdmi <- cormi[1,3]
corrbmi <- cormi[2,3]
data.frame(corrdmi, corrbmi)
```


4. (c)

```{r, include = TRUE, message = FALSE}
fitri <- lm(recovtime ~ ., data = databp)
summary(fitri)

predri <- predict(fitri, newdata = databp)
data.frame(predri[4], predri[10], predri[22])

rtri <- ifelse(is.na(databp$recovtime), predri, databp$recovtime)  
datari <- data.frame(databp[,1:2],rtri)

mri <- mean(rtri)
seri <- sd(rtri)/sqrt(n)
data.frame(mri, seri)

plot(fitri$fitted.values, residuals(fitri), 
     xlab = "Fitted values", ylab = "Residuals")
qqnorm(rstandard(fitri))
qqline(rstandard(fitri), col = 2)


corri <- cor(datari, method = "pearson")
corrdri <- corri[1,3]
corrbri <- corri[2,3]
data.frame(corrdri, corrbri)
```



4. (d)

```{r, include = TRUE, message = FALSE}
set.seed(1)
predsri <- predict(fitri, newdata = databp) + rnorm(n, 0, sigma(fitri))
data.frame(predsri[4], predsri[10], predsri[22])

rtsri <- ifelse(is.na(databp$recovtime), predsri, databp$recovtime)  
datasri <- data.frame(databp[,1:2],rtsri)

msri <- mean(rtsri)
sesri <- sd(rtsri)/sqrt(n)
data.frame(msri, sesri)

corsri <- cor(datasri, method = "pearson")
corrdsri <- corsri[1,3]
corrbsri <- corsri[2,3]
data.frame(corrdsri, corrbsri)
```


4. (e)

```{r, include = TRUE, message = FALSE}
datahd <- databp
names(datahd)[3] <- "rthd"
indna <- which(is.na(databp$recovtime))
predhd <- predri[-indna]

for (i in indna) {
  closest <- names(which.min((predhd-predri[i])^2))
  datahd$rthd[i] = predri[as.numeric(closest)]
}



mhd <- mean(datahd$rthd)
sehd <- sd(datahd$rthd)/sqrt(n)
data.frame(mhd)
data.frame(mhd, sehd)
corhd <- cor(datahd, method = "pearson")
corrdhd <- corhd[1,3]
corrbhd <- corhd[2,3]
data.frame(corrdhd, corrbhd)
```



